name: ML Training Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MLFLOW_PORT: 5000

jobs:
  train:
    runs-on: ubuntu-latest

    services:
      mlflow:
        image: mlflow/mlflow
        ports:
          - ${{ env.MLFLOW_PORT }}:${{ env.MLFLOW_PORT }}
        env:
          MLFLOW_ARTIFACT_ROOT: ./mlruns
        options: >-
          --health-cmd "curl -f http://localhost:${{ env.MLFLOW_PORT }} || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mlflow torch torchvision tqdm scikit-learn matplotlib

      - name: Train model
        run: |
          python train.py \
            --tracking-uri http://localhost:${{ env.MLFLOW_PORT }} \
            --epochs 5 \
            --batch-size 256 \
            --lr 0.001

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-data
          path: |
            ./mlruns
            ./confusion_matrix.png
          retention-days: 7
